export const LOAD_RECEIPE_SUCCESS = 'LOAD_RECEIPE_SUCCESS';
export const LOAD_AUTHOR_SUCCESS = 'LOAD_AUTHOR_SUCCESS';
export const CREATE_RECEIPE_SUCCESS = 'CREATE_RECEIPE_SUCCESS';
export const UPDATE_RECEIPE_SUCCESS = 'UPDATE_RECEIPE_SUCCESS';