import delay from './delay';

const recipes = [{"id":1,"publishDate":"2016-07-06T23:13:22Z","name":"Jabbersphere","slug":"jabbersphere","category":"Desserts","chef":"Javier Orrillo","preparation":"Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\n\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.","ingredients":[{"name":"Andalax","amount":"#c75"},{"name":"Keylex","amount":"#119"},{"name":"Holdlamis","amount":"#209"}]},
{"id":2,"publishDate":"2016-03-01T15:48:37Z","name":"Skiptube","slug":"skiptube","category":"Salads","chef":"Gastón Acurio","preparation":"Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.","ingredients":[{"name":"Cardify","amount":"#27c"}]},
{"id":3,"publishDate":"2016-02-23T13:55:44Z","name":"Jayo","slug":"jayo","category":"Salads","chef":"Javier Orrillo","preparation":"Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.","ingredients":[{"name":"Y-Solowarm","amount":"#b3e"},{"name":"Voyatouch","amount":"#0a1"},{"name":"Namfix","amount":"#bbb"}]},
{"id":4,"publishDate":"2016-01-29T02:22:02Z","name":"Skimia","slug":"skimia","category":"Pastas","chef":"Javier Wong","preparation":"Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\n\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.","ingredients":[{"name":"Fintone","amount":"#5bc"}]},
{"id":5,"publishDate":"2016-07-18T11:10:38Z","name":"Devpoint","slug":"devpoint","category":"Pastas","chef":"Javier Orrillo","preparation":"Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.","ingredients":[{"name":"Opela","amount":"#da5"},{"name":"Sonair","amount":"#223"},{"name":"Zoolab","amount":"#352"},{"name":"Mat Lam Tam","amount":"#5d1"},{"name":"Otcom","amount":"#3a5"}]},
{"id":6,"publishDate":"2016-06-14T11:38:59Z","name":"Twinte","slug":"twinte","category":"Pastas","chef":"Javier Orrillo","preparation":"Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.\n\nCurabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.","ingredients":[{"name":"Trippledex","amount":"#5e2"},{"name":"Greenlam","amount":"#398"},{"name":"Tin","amount":"#613"},{"name":"Sonsing","amount":"#409"},{"name":"Tresom","amount":"#3c1"}]},
{"id":7,"publishDate":"2016-02-20T00:27:57Z","name":"Kwilith","slug":"kwilith","category":"Salads","chef":"Javier Orrillo","preparation":"Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.","ingredients":[{"name":"Wrapsafe","amount":"#e61"},{"name":"Bitwolf","amount":"#8d7"},{"name":"Cardify","amount":"#da2"},{"name":"Stringtough","amount":"#b26"},{"name":"Transcof","amount":"#b24"}]},
{"id":8,"publishDate":"2016-06-11T17:51:49Z","name":"Wordtune","slug":"wordtune","category":"Pastas","chef":"Javier Wong","preparation":"Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\n\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.","ingredients":[{"name":"Daltfresh","amount":"#7c3"},{"name":"Lotlux","amount":"#27a"}]},
{"id":9,"publishDate":"2016-03-08T03:41:12Z","name":"Gabvine","slug":"gabvine","category":"Pastas","chef":"Gastón Acurio","preparation":"Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.","ingredients":[{"name":"Stringtough","amount":"#313"},{"name":"Solarbreeze","amount":"#62a"},{"name":"Zathin","amount":"#ff4"},{"name":"Matsoft","amount":"#cb8"}]},
{"id":10,"publishDate":"2016-05-28T09:30:25Z","name":"Yakitri","slug":"yakitri","category":"Desserts","chef":"Gastón Acurio","preparation":"Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\n\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.","ingredients":[{"name":"Trippledex","amount":"#521"},{"name":"Redhold","amount":"#dc4"},{"name":"Stringtough","amount":"#f93"},{"name":"Kanlam","amount":"#9b5"},{"name":"Cookley","amount":"#a5a"}]},
{"id":11,"publishDate":"2016-08-13T19:44:12Z","name":"Miboo","slug":"miboo","category":"Salads","chef":"Javier Orrillo","preparation":"Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.","ingredients":[{"name":"Veribet","amount":"#c56"},{"name":"Opela","amount":"#fb6"},{"name":"Kanlam","amount":"#d67"}]},
{"id":12,"publishDate":"2016-08-28T10:06:35Z","name":"Twinte","slug":"twinte","category":"Salads","chef":"Gastón Acurio","preparation":"Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.","ingredients":[{"name":"Fixflex","amount":"#8d6"},{"name":"Holdlamis","amount":"#df9"},{"name":"Treeflex","amount":"#2ad"}]},
{"id":13,"publishDate":"2016-04-27T21:39:10Z","name":"Avavee","slug":"avavee","category":"Pastas","chef":"Javier Orrillo","preparation":"Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.","ingredients":[{"name":"Tresom","amount":"#13a"},{"name":"Stim","amount":"#1a0"},{"name":"Stronghold","amount":"#96c"}]},
{"id":14,"publishDate":"2016-04-07T02:09:11Z","name":"Devpulse","slug":"devpulse","category":"Meat","chef":"Javier Wong","preparation":"Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.","ingredients":[{"name":"Bitwolf","amount":"#f88"},{"name":"Rank","amount":"#9e0"}]},
{"id":15,"publishDate":"2016-06-13T22:08:29Z","name":"Gabtype","slug":"gabtype","category":"Desserts","chef":"Gastón Acurio","preparation":"Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.","ingredients":[{"name":"Alphazap","amount":"#c2a"}]},
{"id":16,"publishDate":"2016-07-31T09:37:16Z","name":"Pixoboo","slug":"pixoboo","category":"Desserts","chef":"Gastón Acurio","preparation":"In congue. Etiam justo. Etiam pretium iaculis justo.\n\nIn hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.","ingredients":[{"name":"Duobam","amount":"#bfc"},{"name":"Andalax","amount":"#cc5"},{"name":"Opela","amount":"#cc3"},{"name":"Regrant","amount":"#46e"}]},
{"id":17,"publishDate":"2016-01-11T03:54:42Z","name":"Quamba","slug":"quamba","category":"Pastas","chef":"Javier Wong","preparation":"Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\n\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.","ingredients":[{"name":"Holdlamis","amount":"#816"}]},
{"id":18,"publishDate":"2016-05-12T14:30:01Z","name":"Realcube","slug":"realcube","category":"Desserts","chef":"Javier Wong","preparation":"Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.\n\nCurabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.","ingredients":[{"name":"Span","amount":"#faf"},{"name":"Treeflex","amount":"#49c"},{"name":"Aerified","amount":"#2a9"},{"name":"Stringtough","amount":"#c16"},{"name":"Home Ing","amount":"#769"}]}];

class RecipeApi {
  static getAllRecipes() {
    return new Promise((resolve, reject) => {
      setTimeout(() => {
        resolve(Object.assign([], recipes));
      }, delay);
    });
  }
}

export default RecipeApi;